export enum IconNames {
  bell = 'bell',
  briefcase = 'briefcase',
  heart = 'heart',
  search_alt = 'search-alt',
  plus = 'plus',
  envelope_alt = 'envelope-alt',
  eye = 'eye',
  eye_slash = 'eye-slash',
  padlock = 'padlock',
  lock_alt = 'lock-alt',
  user = 'user',
  filter_slash = 'filter-slash',
  redo = 'redo',
  sign_alt = 'sign-alt',
  arrow_circle_up = 'arrow-circle-up',
  bars = 'bars',
  estate = 'estate',
  calendarAlt = 'calendar-alt',
  usersAlt = 'users-alt',
  infoCircle = 'info-circle',
  signInAlt = 'sign-in-alt',
  times = 'times',
  arrowRight = 'arrow-right'
}
